// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Domain;

#nullable disable

namespace SegurosDelPacifico.web.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231222090343_empleados")]
    partial class empleados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Models.Domain.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SalarioBase")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Models.Domain.Salario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSalario")
                        .HasColumnType("TEXT");

                    b.Property<double>("Horas")
                        .HasColumnType("REAL");

                    b.Property<double>("HorasExtra")
                        .HasColumnType("REAL");

                    b.Property<double>("MontoDeduciones")
                        .HasColumnType("REAL");

                    b.Property<int>("PorcentajeDeduciones")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioNeto")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Salarios");
                });

            modelBuilder.Entity("Models.Domain.Salario", b =>
                {
                    b.HasOne("Models.Domain.Empleado", null)
                        .WithMany("Salarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Domain.Empleado", b =>
                {
                    b.Navigation("Salarios");
                });
#pragma warning restore 612, 618
        }
    }
}
